// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ywjcqnrappksokerzixb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl3amNxbnJhcHBrc29rZXJ6aXhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwNjE3NDUsImV4cCI6MjA3NDYzNzc0NX0.HS9COqBuVWSbS32hpE9XYgf-6I4nd6JkvgpRmd5H-Jc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});